version: '3'

services:

  redis:
    image: redis:3.2.9-alpine
    ports:
    - 6379:6379/tcp
    restart: always

  postgres:
    environment:
      POSTGRES_DB: mydb
      POSTGRES_PASSWORD: 'mypassword'
      POSTGRES_USER: myuser
    image: postgres:9.5.7-alpine
    ports:
    - 5432:5432/tcp
    restart: always
